# Generated by Django 3.1 on 2020-08-29 01:45

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import message.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('type', enumfields.fields.EnumIntegerField(default=0, enum=message.models.MessageType)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
