# Generated by Django 3.1 on 2020-08-13 16:31

from django.db import migrations, models
import django.db.models.deletion
import dorm.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(max_length=10)),
                ('room_number', models.IntegerField(max_length=10)),
                ('capacity', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationsInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_to_user2_state', enumfields.fields.EnumIntegerField(default=-1, enum=dorm.models.RelationStateType)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.account')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.account')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Room_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_state', enumfields.fields.EnumIntegerField(default=-1, enum=dorm.models.StateType)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
