# Generated by Django 3.1 on 2020-08-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='room_user',
            unique_together=set(),
        ),
    ]
