# Generated by Django 3.1 on 2020-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_auto_20200813_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
