# Generated by Django 3.1 on 2020-08-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dorm', '0003_auto_20200814_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
